
- GeoPandas import 오류
- OSError: Could not find libspatialindex_c library file
~~~
root@DataLX01:~# apt install python3-rtree
패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다       
상태 정보를 읽는 중입니다... 완료
다음 패키지가 자동으로 설치되었지만 더 이상 필요하지 않습니다:
  cuda-9-1 cuda-command-line-tools-9-1 cuda-compiler-9-1 cuda-cublas-9-1 cuda-cublas-dev-9-1 cuda-cudart-9-1
  cuda-cudart-dev-9-1 cuda-cufft-9-1 cuda-cufft-dev-9-1 cuda-cuobjdump-9-1 cuda-cupti-9-1 cuda-curand-9-1
  cuda-curand-dev-9-1 cuda-cusolver-9-1 cuda-cusolver-dev-9-1 cuda-cusparse-9-1 cuda-cusparse-dev-9-1
  cuda-demo-suite-9-1 cuda-documentation-9-1 cuda-driver-dev-9-1 cuda-gdb-9-1 cuda-gpu-library-advisor-9-1
  cuda-libraries-9-1 cuda-libraries-dev-9-1 cuda-license-9-1 cuda-memcheck-9-1 cuda-misc-headers-9-1 cuda-npp-9-1
  cuda-npp-dev-9-1 cuda-nsight-9-1 cuda-nvcc-9-1 cuda-nvdisasm-9-1 cuda-nvgraph-9-1 cuda-nvgraph-dev-9-1
  cuda-nvml-dev-9-1 cuda-nvprof-9-1 cuda-nvprune-9-1 cuda-nvrtc-9-1 cuda-nvrtc-dev-9-1 cuda-nvtx-9-1 cuda-nvvp-9-1
  cuda-runtime-9-1 cuda-samples-9-1 cuda-toolkit-9-1 cuda-tools-9-1 cuda-visual-tools-9-1 libdbusmenu-gtk4 libllvm5.0
  linux-headers-4.4.0-119 linux-headers-4.4.0-119-generic linux-image-4.4.0-119-generic
  linux-image-extra-4.4.0-119-generic linux-signed-image-4.4.0-119-generic
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libspatialindex-c4v5 libspatialindex-dev libspatialindex4v5
다음 새 패키지를 설치할 것입니다:
  libspatialindex-c4v5 libspatialindex-dev libspatialindex4v5 python3-rtree
0개 업그레이드, 4개 새로 설치, 0개 제거 및 127개 업그레이드 안 함.
579 k바이트 아카이브를 받아야 합니다.
이 작업 후 3,480 k바이트의 디스크 공간을 더 사용하게 됩니다.
계속 하시겠습니까? [Y/n] Y
받기:1 http://mirror.kakao.com/ubuntu xenial/universe amd64 libspatialindex4v5 amd64 1.8.5-3 [220 kB]
받기:2 http://mirror.kakao.com/ubuntu xenial/universe amd64 libspatialindex-c4v5 amd64 1.8.5-3 [52.2 kB]
받기:3 http://mirror.kakao.com/ubuntu xenial/universe amd64 libspatialindex-dev amd64 1.8.5-3 [291 kB]
받기:4 http://mirror.kakao.com/ubuntu xenial/universe amd64 python3-rtree all 0.8.2+ds-2 [15.7 kB]
내려받기 579 k바이트, 소요시간 0초 (2,424 k바이트/초)
Selecting previously unselected package libspatialindex4v5:amd64.
(데이터베이스 읽는중 ...현재 409808개의 파일과 디렉터리가 설치되어 있습니다.)
Preparing to unpack .../libspatialindex4v5_1.8.5-3_amd64.deb ...
Unpacking libspatialindex4v5:amd64 (1.8.5-3) ...
Selecting previously unselected package libspatialindex-c4v5:amd64.
Preparing to unpack .../libspatialindex-c4v5_1.8.5-3_amd64.deb ...
Unpacking libspatialindex-c4v5:amd64 (1.8.5-3) ...
Selecting previously unselected package libspatialindex-dev:amd64.
Preparing to unpack .../libspatialindex-dev_1.8.5-3_amd64.deb ...
Unpacking libspatialindex-dev:amd64 (1.8.5-3) ...
Selecting previously unselected package python3-rtree.
Preparing to unpack .../python3-rtree_0.8.2+ds-2_all.deb ...
Unpacking python3-rtree (0.8.2+ds-2) ...
libspatialindex4v5:amd64 (1.8.5-3) 설정하는 중입니다 ...
libspatialindex-c4v5:amd64 (1.8.5-3) 설정하는 중입니다 ...
libspatialindex-dev:amd64 (1.8.5-3) 설정하는 중입니다 ...
python3-rtree (0.8.2+ds-2) 설정하는 중입니다 ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
/sbin/ldconfig.real: file /usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.7 is truncated

root@DataLX01:~# 


~~~
- 해결해야할 듯...
~~~
root@DataLX01:~# pip install geos -U
Looking in indexes: http://ftp.daumkakao.com/pypi/simple
Collecting geos
  Downloading http://mirror.kakao.com/pypi/packages/9e/12/5b5fa771d309a6aeb284fcd27cf2db93148926c23787e4e9072d90373ed5/geos-0.2.1-py3-none-any.whl (367kB)
    100% |████████████████████████████████| 368kB 3.2MB/s 
Requirement already satisfied, skipping upgrade: flask in /usr/local/lib/python3.6/dist-packages (from geos) (1.0.2)
Requirement already satisfied, skipping upgrade: lxml in /usr/local/lib/python3.6/dist-packages (from geos) (4.1.1)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages (from flask->geos) (0.24)
Requirement already satisfied, skipping upgrade: click>=5.1 in /usr/local/lib/python3.6/dist-packages (from flask->geos) (7.0)
Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in /usr/local/lib/python3.6/dist-packages (from flask->geos) (0.14.1)
Requirement already satisfied, skipping upgrade: Jinja2>=2.10 in /usr/local/lib/python3.6/dist-packages (from flask->geos) (2.10)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from Jinja2>=2.10->flask->geos) (1.0)
Installing collected packages: geos
Successfully installed geos-0.2.1
root@DataLX01:~# pip install contextily -U
Looking in indexes: http://ftp.daumkakao.com/pypi/simple
Collecting contextily
  Downloading http://mirror.kakao.com/pypi/packages/10/34/2aabf40c1acfb4b2f623e90f1a130eba80fd664a2d91c801558acebe3d3c/contextily-0.99.0.tar.gz
Collecting cartopy (from contextily)
  Downloading http://mirror.kakao.com/pypi/packages/e5/92/fe8838fa8158931906dfc4f16c5c1436b3dd2daf83592645b179581403ad/Cartopy-0.17.0.tar.gz (8.9MB)
    100% |████████████████████████████████| 8.9MB 10.8MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    /tmp/pip-install-dfbs505w/cartopy/setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    Proj 4.9.0 must be installed.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dfbs505w/cartopy/
root@DataLX01:~# pip list | grep cont
contextlib2                   0.5.5                 
contractions                  0.0.16                
zope.container                4.2.2                 
zope.contentprovider          4.1.0                 
zope.contenttype              4.3.0                 
root@DataLX01:~# pip install pyproj -U
Looking in indexes: http://ftp.daumkakao.com/pypi/simple
Requirement already up-to-date: pyproj in /usr/local/lib/python3.6/dist-packages (1.9.6)
root@DataLX01:~# pip install cartopy -U
Looking in indexes: http://ftp.daumkakao.com/pypi/simple
Collecting cartopy
  Downloading http://mirror.kakao.com/pypi/packages/e5/92/fe8838fa8158931906dfc4f16c5c1436b3dd2daf83592645b179581403ad/Cartopy-0.17.0.tar.gz (8.9MB)
    100% |████████████████████████████████| 8.9MB 9.0MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    /tmp/pip-install-jw_jqu8t/cartopy/setup.py:171: UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.
      '.'.join(str(v) for v in GEOS_MIN_VERSION), ))
    Proj 4.9.0 must be installed.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jw_jqu8t/cartopy/
root@DataLX01:~# 
~~~
